language: node_js
node_js:
  - 4.0
  - 4.1
  - 4.2
  - 5.0
  - 5.1
  - 5.2
  - 5.3
  - 5.4
sudo: false
before_install: npm install -g grunt-cli
install: npm install
#before_script:
#script:
#after_success:
#after_failure:
#after_script:
